[project]
name = "deeptaxa-rrna"
dynamic = ["version"]
requires-python = ">=3.10"
description = "A deep learning framework for hierarchical taxonomy classification of 16S rRNA gene sequences."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Ahmed Moustafa", email = "amoustafa@aucegypt.edu" },
    { name = "Rana Salah", email = "rana_salah@aucegypt.edu" },
    { name = "Khlood Ramadan", email = "khlood.ramadan@aucegypt.edu" },
    { name = "Lobna Ghonaim", email = "lobnaghonaim@aucegypt.edu" }
]
maintainers = [
    { name = "Ahmed Moustafa", email = "amoustafa@aucegypt.edu" }
]
dependencies = [
    "torch>=2.0",
    "numpy",
    "transformers>=4.28",
    "pandas",
    "tqdm",
    "scikit-learn",
    "biopython",
    "h5py",
    "optuna"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent"
]

[project.scripts]
deeptaxa = "deeptaxa.cli:main"

[project.entry-points."qiime2.plugins"]
q2-deeptaxa = "q2_deeptaxa.plugin_setup:plugin"

[project.urls]
Homepage = "https://github.com/systems-genomics-lab/deeptaxa"
Repository = "https://github.com/systems-genomics-lab/deeptaxa"
Documentation = "https://systems-genomics-lab.github.io/deeptaxa/"
"Bug Tracker" = "https://github.com/systems-genomics-lab/deeptaxa/issues"

[build-system]
requires = ["setuptools>=77", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["deeptaxa*", "q2_deeptaxa*"]
exclude = ["data", "outputs", "predictions", "logs"]

[tool.setuptools.package-data]
q2_deeptaxa = ["citations.bib"]

[tool.setuptools_scm]
version_scheme = "release-branch-semver"
local_scheme = "no-local-version"

